name: Build the project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi make

      - name: Run Make
        run: make

